# Generated by Django 4.2 on 2026-01-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='created_at',
        ),
        migrations.AddField(
            model_name='election',
            name='contract_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together={('wallet_address', 'election')},
        ),
        migrations.RemoveField(
            model_name='voter',
            name='is_verified',
        ),
    ]
