# Generated by Django 4.2 on 2026-01-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_remove_election_created_at_election_contract_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='is_active',
        ),
        migrations.AddField(
            model_name='election',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='election',
            name='contract_address',
            field=models.CharField(default='0x0000000000000000000000000000000000000000', max_length=42, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
